apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    nginx.ingress.kubernetes.io/auth-url: "https://auth.dariomazza.net/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.dariomazza.net/oauth2/start?rd=$scheme://$host$escaped_request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - longhorn.dariomazza.net 
      secretName: longhorn-tls
  rules:
  - host: longhorn.dariomazza.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80