apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-tailscale
  name: longhorn-tailscale
  namespace: longhorn
  annotations:                
    tailscale.com/expose: "true"
    tailscale.com/hostname: "longhorn"
    tailscale.com/tags: "tag:k8s-operator"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: longhorn-ui
  type: ClusterIP
status:
  loadBalancer: {}
