apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-azuread-creds
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: grafana-azuread-creds # Name of the K8s Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Construct full URLs using the retrieved Tenant ID
        GF_AUTH_AZUREAD_AUTH_URL: "https://login.microsoftonline.com/{{ .tenant_id }}/oauth2/v2.0/authorize"
        GF_AUTH_AZUREAD_TOKEN_URL: "https://login.microsoftonline.com/{{ .tenant_id }}/oauth2/v2.0/token"
        GF_AUTH_AZUREAD_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_AZUREAD_CLIENT_SECRET: "{{ .client_secret }}"
        GF_AUTH_AZUREAD_ALLOWED_ORGANIZATIONS: "{{ .tenant_id }}"
  data:
  - secretKey: client_id
    remoteRef:
      key: grafana-client-id # Key in Azure Key Vault
  - secretKey: client_secret
    remoteRef:
      key: grafana-client-secret
  - secretKey: tenant_id
    remoteRef:
      key: grafana-tenant-id
