grafana:
  deploymentStrategy:
    type: Recreate
  admin:
    existingSecret: "grafana-secret"
    userKey: "admin-user"
    passwordKey: "admin-password"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    hosts:
      - grafana.dariomazza.net
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.dariomazza.net

  persistence:
    enabled: true
    size: 5Gi
    storageClassName: "longhorn-ssd"



prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn-ssd"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
