apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:vact+QjYIw9eBD8m8e2ymw==,iv:m9HXD3PMONW5CNO0Y0EwjF8eyE5RAZ3dJ6uD4u3VWGg=,tag:jSTN/2qBB8xtXFW2kgctFw==,type:str]
    admin-user: ENC[AES256_GCM,data:nnOhobuj6f4=,iv:FprPdkYcIABxRsh+SIneDeYONKbHYmS86qWi1//jXoM=,tag:5HUo81jGSkzVsGYCy8qZnQ==,type:str]
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
sops:
    age:
        - recipient: age1hj9gxc8xjg96lpjqk29ay98zsy3j9j7lxygpj4hgfh85vpmd35rstj5qzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ1g4ZUNpcnFsUHVCR05E
            Y3phSG1aNHBjR0VLaHVHMjF6TzFWTXJ5YndrCk9LNnJLK0x4ME5BcVZRZjJCR09X
            UjVieVFtcnZhSXpmOWVvcVVLbFBlVTAKLS0tIDdFRGJaS0tvUzhmTUdHNWNhbG5S
            UVRsK1RoSmhZSVd1eUdsbi9vVGU0SDQKrH1d2wUbZ1qjE1hrTaLLZGjQlA/kSTNK
            03oays6foJkKX0CRpIbOCLMAcYf+NdgRy50MY9h8lZp/ViSnRHAe/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T11:31:40Z"
    mac: ENC[AES256_GCM,data:YuU0/QwJamJ9RNw2nqkmgFV47/8bSaxt3zqZegOMQna7VGVbVQAotQeCDmJAoc1AMCUIg7MPu5/74ZAOad2OsST/97jdwqUWF4eDS/xsvbo1zSginG80C/KF/IZ23JVPmv8jB7/z28x3vZezOanfowxQdNfpK5rZtMiHnBYzxzQ=,iv:XmQQkqI/HywxMEBs7nhXa1Ro4TjPRS58p4BMLEXkplk=,tag:gddAqVK3+DlFJaorFyRSLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
