apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
spec:
  template:
    spec:
      containers:
        - name: glance
          envFrom:
            - secretRef:
                name: glance-google-secret
            - secretRef:
                name: glance-github-secret
