apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance
resources:
  - ../../base/glance
  - namespace.yaml
  - ingress.yaml
  - google-secret.yaml

patches:
  - path: config-map-patch.yaml
  - path: deployment-patch.yaml
