apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infra-controllers.yaml
  - infra-configs.yaml
  - monitoring-controllers.yaml
  - monitoring-configs.yaml
  - apps-production.yaml
  - apps-staging.yaml
  - private-source.yaml
