apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: longhorn-backup-secret
    template:
      type: Opaque
      data:
        AZBLOB_ACCOUNT_NAME: "stdariomazzahomelab"
        AZBLOB_ACCOUNT_KEY: "{{ .AZBLOB_ACCOUNT_KEY }}"
        AZBLOB_ENDPOINT: "blob.core.windows.net"
  data:
  - secretKey: AZBLOB_ACCOUNT_KEY
    remoteRef:
      key: longhorn-backup-key
