apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: longhorn-backup-secret
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "stdariomazzahomelab"
        AWS_ENDPOINTS: "https://stdariomazzahomelab.blob.core.windows.net"
  data:
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: longhorn-backup-key
