apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio
spec:
  ports:
  - name: hhtp
    port: 80
    protocol: TCP
    targetPort: 4321
  selector:
    app: portfolio
  type: ClusterIP

