apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-homelab
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: private-homelab
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        identity: "{{ .identity }}"
        identity.pub: "{{ .identity_pub }}"
  data:
  - secretKey: identity
    remoteRef:
      key: private-homelab-identity
  - secretKey: identity_pub
    remoteRef:
      key: private-homelab-identity-pub
