apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/podinfo
  - ingress.yaml
  - namespace.yaml

namespace: podinfo-staging

nameSuffix: -staging

patches:
  - path: message.yaml
