apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  # --- Settings ---
  settings.yaml: |
    title: Dario's Homelab
    background:
      image: https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop
      opacity: 0.5
    layout:
      My Applications:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 4

  # --- Services ---
  services.yaml: |
    - My Applications:
        - Portfolio:
            icon: https://dariomazza.net/favicon.ico
            href: https://dariomazza.net
            description: My Personal Website
        - Podinfo:
            icon: https://raw.githubusercontent.com/stefanprodan/podinfo/master/logo.png
            href: https://podinfo.dariomazza.net
            description: Go Microservice Demo

    - Infrastructure:
        - FritzBox:
            icon: https://upload.wikimedia.org/wikipedia/commons/f/f6/Fritz%21Box-Logo.svg
            href: http://192.168.1.1
            description: Router Gateway
        - Grafana:
            icon: grafana.png
            href: https://grafana.dariomazza.net
            description: Monitoring & Observability
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.dariomazza.net
            description: Distributed Block Storage

  # --- Bookmarks ---
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/xDaryamo
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
    - Social & Personal:
        - Google:
            - abbr: GO
              href: https://google.com
        - Gmail:
            - abbr: GM
              href: https://mail.google.com
        - LinkedIn:
            - abbr: LI
              href: https://www.linkedin.com
        - YouTube:
            - abbr: YT
              href: https://www.youtube.com

  # --- Widgets ---
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        memory: true
        disk: /
        expanded: true
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: 2xl
        format:
          timeStyle: short
          dateStyle: long