apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  # --- Settings ---
  settings.yaml: |
    title: Dario's Homelab
    background:
      image: https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=2070&auto=format&fit=crop
      opacity: 0.5
    layout:
      My Applications:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 4

  # --- Services ---
  services.yaml: |
    - My Applications:
        - Portfolio:
            icon: https://dariomazza.net/favicon.ico
            href: https://dariomazza.net
            description: My Personal Website
        - Podinfo:
            icon: https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif
            href: https://podinfo.dariomazza.net
            description: Go Microservice Demo

    - Infrastructure:
        - FritzBox:
            icon: https://fritz.com/cdn/shop/files/favicon_1_7cec16c7-3e78-4ee4-a825-55a17af30f8c.svg?crop=center&height=32&v=1766083933&width=32
            href: http://192.168.1.1
            description: Router Gateway
        - Grafana:
            icon: grafana.png
            href: https://grafana.dariomazza.net
            description: Monitoring & Observability
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.dariomazza.net
            description: Distributed Block Storage

  # --- Bookmarks ---
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              icon: github.png
              href: https://github.com/xDaryamo
        - Cloudflare:
            - abbr: CF
              icon: cloudflare.png
              href: https://dash.cloudflare.com/
    - Social & Personal:

        - Google:
            - abbr: GO
              icon: google.png
              href: https://google.com
        - Gmail:
            - abbr: GM
              icon: gmail.png
              href: https://mail.google.com
        - YouTube:
            - abbr: YT
              icon: youtube.png
              href: https://www.youtube.com
        - Gemini:
            - abbr: GE
              icon: google-gemini.png
              href: https://gemini.google.com
        - LinkedIn:
            - abbr: LI
              icon: linkedin.png
              href: https://www.linkedin.com

  # --- Widgets ---
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Cluster Total"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: 2xl
        format:
          timeStyle: short
          dateStyle: long