apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - external-secrets
  - cert-manager
  - cloudflared
  - external-dns
  - renovate
  - longhorn
  - oauth2-proxy
  - private-homelab
