apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secret
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv
  target:
    name: oauth2-proxy-secret
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: oauth2-proxy-client-id
    - secretKey: client_secret
      remoteRef:
        key: oauth2-proxy-client-secret
    - secretKey: cookie_secret
      remoteRef:
        key: oauth2-proxy-cookie-secret
