apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token-secret
  namespace: cloudflared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: cloudflared-token-secret
    creationPolicy: Owner
  data:
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: cloudflared-token
