apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio-staging
resources:
  - ../../base/portfolio
  - namespace.yaml

namePrefix: staging-

images:
  - name: ghcr.io/xdaryamo/portfolio
    newTag: latest