apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio-staging
resources:
  - ../../base/portfolio
  - namespace.yaml

namePrefix: staging-

patches:
  - path: ingress.yaml
  - path: scaling.yaml

images:
  - name: ghcr.io/xdaryamo/portfolio
    newTag: 2.1.2