apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocard
  labels:
    app: vocard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vocard
  template:
    metadata:
      labels:
        app: vocard
    spec:
      initContainers:
        - name: init-config
          image: busybox:latest
          command: ['sh', '-c', 'cp /config/settings.json /app/settings.json']
          volumeMounts:
            - name: settings-secret
              mountPath: /config
            - name: settings-volume
              mountPath: /app
      containers:
        - name: vocard
          image: ghcr.io/chocomeow/vocard:v2.7.2
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: settings-volume
              mountPath: /app/settings.json
              subPath: settings.json
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
      volumes:
        - name: settings-secret
          secret:
            secretName: vocard-settings
        - name: settings-volume
          emptyDir: {}
