apiVersion: apps/v1
kind: Deployment
metadata:
  name: vocard
  labels:
    app: vocard
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vocard
  template:
    metadata:
      labels:
        app: vocard
    spec:
      containers:
        - name: vocard
          image: ghcr.io/chocomeow/vocard:v2.7.2
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: settings
              mountPath: /app/settings.json
              subPath: settings.json
              readOnly: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
      volumes:
        - name: settings
          secret:
            secretName: vocard-settings
