apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-token-secret
  namespace: renovate
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: renovate-token-secret
    creationPolicy: Owner
  data:
  - secretKey: RENOVATE_TOKEN
    remoteRef:
      key: renovate-token
