apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: "https://kv-dariomazza-homelab.vault.azure.net"
      tenantId: "c30767db-3dda-4dd4-8a4d-097d22cb99d3"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: azure-secret-sp
          key: client-secret
          namespace: external-secrets
